[features]
seeds = false
skip-lint = false

[programs.localnet]
otakuverse_program = "6WVQUSeRZPpZDukYxKc1gLjG1hRtUMHCGpvoC7vsEFw1"

[programs.devnet]
otakuverse_program = "6WVQUSeRZPpZDukYxKc1gLjG1hRtUMHCGpvoC7vsEFw1"

[programs.testnet]
otakuverse_program = "6WVQUSeRZPpZDukYxKc1gLjG1hRtUMHCGpvoC7vsEFw1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../otakuverse-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
